build_image_dev:
	docker build . -t joanferrecid098/ww-v1:0.1.0

run_image_dev: 
	docker run -d -p 8080:8080 --name ww-v1 -e GROUPS='{"groups":[{"display":"asjdl", "name":"Jijijija"}]}' joanferrecid098/ww-v1:0.1.0